var products = [{
  "notes": [{
    "header": "Untitled_3",
    "description": "",
    "type": "Title & Teaser",
    "id": "2f913782",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_3",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 3,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "72f29f41", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_3",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  }
}, {
  "notes": [{
    "header": "Untitled_2",
    "description": "",
    "type": "Title & Teaser",
    "id": "17360260",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_2",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 2,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "4ba312b1", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_2",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  }
}, {
  "notes": [{
    "header": "Untitled_1",
    "description": "",
    "type": "Title & Teaser",
    "id": "0ea71b6c",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": ""
  }],
  "label": "Untitled_1",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": [{
    "id": "RURFS0FAVEFHQEJyYW5k",
    "name": "EDEKA",
    "relevance": "-100"
  }, {
    "id": "RURFS0EgQ2VudGVyQFRBR0BCcmFuZA==",
    "name": "EDEKA Center",
    "relevance": "54"
  }, {"id": "RURFS0EgUmVpY2hlbHRAVEFHQEJyYW5k", "name": "EDEKA Reichelt", "relevance": "100"}],
  "Market Cluster": [],
  "Content Score": [],
  "Communication Channel": "",
  "Promotion": "",
  "Quality": [],
  "Region": [],
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 1,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": [],
  "title": "Untitled_1",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "Communication channel": [],
  "checkedTagGroups": {
    "Brand": ["EDEKA", "EDEKA Center", "EDEKA Reichelt"],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }
}];