var products = [{
  "notes": [{
    "header": "Untitled_19",
    "description": "",
    "type": "Title & Teaser",
    "id": "0a1d66a5",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_19",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 19,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "3bae5501", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_19",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001d9ea826b351a4684e23"}
}, {
  "notes": [{
    "header": "Untitled_18",
    "description": "",
    "type": "Title & Teaser",
    "id": "77190e3f",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": ""
  }],
  "label": "Untitled_18",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 18,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_18",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001d00a826b351a4684e21"}
}, {
  "notes": [{
    "header": "Untitled_17",
    "description": "",
    "type": "Title & Teaser",
    "id": "10b898db",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": ""
  }],
  "label": "Untitled_17",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 17,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "Impulse",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_17",
  "blockData": "{\"data\":[]}",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001c80a826b351a4684e1f"}
}, {
  "notes": [{
    "header": "Untitled_16",
    "description": "",
    "type": "Title & Teaser",
    "id": "2ce8cf3c",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": ""
  }],
  "label": "Untitled_16",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 16,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "Semi-structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_16",
  "blockData": "{\"data\":[]}",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001ac7a826b351a4684e1d"}
}, {
  "notes": [{
    "header": "Untitled_15",
    "description": "",
    "type": "Title & Teaser",
    "id": "389beaa3",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_15",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 15,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "739c9595", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_15",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "550018f5a826b351a4684e1b"}
}, {
  "notes": [{
    "header": "Untitled_14",
    "description": "",
    "type": "Title & Teaser",
    "id": "2b9b4c96",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_14",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 14,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "f873487b", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_14",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "5500187da826b351a4684e19"}
}, {
  "notes": [{
    "header": "Untitled_13",
    "description": "",
    "type": "Title & Teaser",
    "id": "95bcc11b",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_13",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 13,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "84cbc65a", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_13",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "5500175ca826b351a4684e17"}
}, {
  "notes": [{
    "header": "Untitled_12",
    "description": "",
    "type": "Title & Teaser",
    "id": "7256d7e4",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_12",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 12,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "3b6c4bcd", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_12",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "5500162fa826b351a4684e15"}
}, {
  "notes": [{
    "header": "Untitled_11",
    "description": "",
    "type": "Title & Teaser",
    "id": "397e3bc0",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_11",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 11,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "3c51213e", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_11",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001527a826b351a4684e13"}
}, {
  "notes": [{
    "type": "Title & Teaser",
    "id": "596656db",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": "",
    "undefined": ""
  }],
  "label": "Untitled_18",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 10,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "CMS",
  "workflowStatus": "Updated",
  "Category": "",
  "title": "Untitled_18",
  "blockData": "{\"data\":[]}",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "550013f2a826b351a4684e11"}
}, {
  "notes": [{
    "header": "Untitled_9",
    "description": "",
    "type": "Title & Teaser",
    "id": "dc50a808",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_9",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 9,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "a00c3b62", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_9",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001358a826b351a4684e0e"}
}, {
  "notes": [{
    "header": "Untitled_8",
    "description": "",
    "type": "Title & Teaser",
    "id": "7593c363",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_8",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 8,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "26e2b6dd", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_8",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "550012d7a826b351a4684e0b"}
}, {
  "notes": [{
    "header": "Untitled_7",
    "description": "",
    "type": "Title & Teaser",
    "id": "e02586e0",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_7",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 7,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "71ea13a7", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_7",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001190a826b351a4684e0a"}
}, {
  "notes": [{
    "header": "Untitled_6",
    "description": "",
    "type": "Title & Teaser",
    "id": "9614247f",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_6",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 6,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "91dcde92", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_6",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "55001039a826b351a4684e07"}
}, {
  "notes": [{
    "header": "Untitled_5",
    "description": "",
    "type": "Title & Teaser",
    "id": "68b1a816",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_5",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 5,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "5a41bc2c", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_5",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "5530ef150364bba2a5c74899"}
}, {
  "notes": [{
    "header": "Untitled_4",
    "description": "",
    "type": "Title & Teaser",
    "id": "d95e1c3c",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_4",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 4,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "c595abca", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_4",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "_id": {"$oid": "5530ef150364bba2a5c74898"}
}, {
  "notes": [{
    "header": "Untitled_3",
    "description": "",
    "type": "Title & Teaser",
    "id": "2f913782",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    }
  }],
  "label": "Untitled_3",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "SAP-CP": "",
  "SAP-RP": "",
  "SAP-Status": "",
  "SAP-Stock": "",
  "SAP-SubSystem": "",
  "SAPId": "",
  "Sales channel": "",
  "currentPrice": "",
  "description": "",
  "discount": "",
  "grill": "",
  "id": 3,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [{"id": "72f29f41", "text": ""}],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_3",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  }
}, {
  "notes": [{
    "header": "Untitled_2",
    "description": "",
    "type": "Title & Teaser",
    "id": "17360260",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": ""
  }],
  "label": "Untitled_2",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": "",
  "Market Cluster": "",
  "Content Score": "",
  "Communication Channel": "",
  "Promotion": "",
  "Quality": "",
  "Region": "",
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 2,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": "",
  "title": "Untitled_2",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  }
}, {
  "notes": [{
    "header": "Untitled_1",
    "description": "",
    "type": "Title & Teaser",
    "id": "0ea71b6c",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "Title & Teaser": ""
  }],
  "label": "Untitled_1",
  "image": ["images/pouch.png"],
  "multimedia": [{
    "image": "images/pouch.png",
    "tags": {
      "Brand": [],
      "Market Cluster": [],
      "Category": [],
      "Region": [],
      "Content Score": [],
      "Communication channel": [],
      "Quality": []
    },
    "name": ""
  }],
  "imageTags": [{
    "Brand": [],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }],
  "comments": "",
  "class": "Standard",
  "Channel": "",
  "Target Group": "",
  "Brand": [{
    "id": "RURFS0FAVEFHQEJyYW5k",
    "name": "EDEKA",
    "relevance": "-100"
  }, {
    "id": "RURFS0EgQ2VudGVyQFRBR0BCcmFuZA==",
    "name": "EDEKA Center",
    "relevance": "54"
  }, {"id": "RURFS0EgUmVpY2hlbHRAVEFHQEJyYW5k", "name": "EDEKA Reichelt", "relevance": "100"}],
  "Market Cluster": [],
  "Content Score": [],
  "Communication Channel": "",
  "Promotion": "",
  "Quality": [],
  "Region": [],
  "Division": "",
  "Sales channel": "",
  "currentPrice": "",
  "discount": "",
  "grill": "",
  "id": 1,
  "imageGrill": "",
  "imageOrganicStamp": "",
  "imageQRCode": "",
  "imageSuperKnuller": "",
  "imageWatchStamp": "",
  "impulse": [],
  "isFolder": "",
  "previousPrice": "",
  "type": "Structured",
  "workflowStatus": "Created",
  "Category": [],
  "title": "Untitled_1",
  "blockData": "",
  "blockNotes": [],
  "richTextData": "",
  "markers": {
    "Brand": {},
    "Market Cluster": {},
    "Category": {},
    "Region": {},
    "Content Score": {},
    "Communication channel": {},
    "Quality": {}
  },
  "Communication channel": [],
  "checkedTagGroups": {
    "Brand": ["EDEKA", "EDEKA Center", "EDEKA Reichelt"],
    "Market Cluster": [],
    "Category": [],
    "Region": [],
    "Content Score": [],
    "Communication channel": [],
    "Quality": []
  }
}];